apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: nginx-proxy-conf
  default.conf: |
    server {
      listen 80;
      location = /favicon.ico {
        return 204;
        access_log off;
        log_not_found off;
      }
      
      location / {
        proxy_pass http://slackbot-service-svc.default.svc.cluster.local:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-proxy-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-proxy-conf
        configMap:
          name: nginx-proxy-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
