#!/bin/bash

# Check if the required arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 image_name version"
    exit 1
fi

# Assign the arguments to variables
image_name=$1
version=$2

# build image
docker build -t "${image_name}:v${version}" .

# connect docker with gcloud
gcloud auth configure-docker

# tag the docker image to the GCR container registry
docker tag "${image_name}:v${version}" "gcr.io/chatbot-alpha-380206/${image_name}:v${version}"

# push the image to GCR container registry
docker push "gcr.io/chatbot-alpha-380206/${image_name}:v${version}"

# ./scripts/build determinant 0.0.1  # build the image