name: Build and Deploy - east

on:
  workflow_dispatch: {}


jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Shutdown existing serve
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.HOST_EAST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY_EAST }}
            port: 22
            script: |
              /home/ubuntu/determinant/venv/bin/serve shutdown -y || true
      - name: Copy files to ec2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_EAST }}
          REMOTE_HOST: ${{ secrets.HOST_EAST }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/determinant
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.HOST_EAST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY_EAST }}
            port: 22
            script: |
              cd determinant
              . venv/bin/activate
              # pip install -r requirements.txt
              cd src/app
              PYTHONPATH="/home/ubuntu/determinant/src" \
              AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }} \
              SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }} \
              SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }} \
              serve run async_rag_app:slack_agent_deployment &> /home/ubuntu/determinant.log
              # serve run async_rag_app:slack_agent_deployment &>/dev/null &
